# Generated by Django 5.1.6 on 2025-05-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customers_options_alter_customers_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customers',
            managers=[
            ],
        ),
    ]
