# Generated by Django 5.1.6 on 2025-05-06 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_favori'),
        ('Users', '0003_alter_customers_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Blanc'), ('dark', 'Sombre')], default='light', max_length=10)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=5)),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA'), ('USD', 'Dollar'), ('EUR', 'Euro')], default='XOF', max_length=5)),
                ('preferred_brands', models.ManyToManyField(blank=True, to='Products.brands')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
