# Generated by Django 5.1.6 on 2025-10-22 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande_items',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='commandes',
            name='address',
            field=models.CharField(default='Godomey', max_length=200),
        ),
        migrations.AddField(
            model_name='commandes',
            name='city',
            field=models.CharField(default='Cotonou', max_length=100),
        ),
        migrations.AddField(
            model_name='commandes',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='commandes',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='commandes',
            name='phone',
            field=models.CharField(default='0190835005', max_length=15),
        ),
        migrations.AddField(
            model_name='commandes',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_items', to='Orders.commandes'),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order_status',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('shipped', 'Expédié')], max_length=20),
        ),
    ]
