# Generated by Django 5.1.6 on 2025-03-25 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('stock_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('alt_text', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.CreateModel(
            name='Casques_ecouteurs',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Products.products')),
                ('battery_life', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PCs',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Products.products')),
                ('core', models.CharField(max_length=20)),
                ('generation', models.CharField(max_length=20)),
                ('pc_type', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('processor', models.CharField(max_length=100)),
                ('graphics_card', models.CharField(max_length=100)),
                ('refresh_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('core_count', models.IntegerField()),
                ('logical_processors', models.IntegerField()),
                ('battery_life', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Smartphones_tablets',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Products.products')),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('camera_pixels', models.IntegerField()),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('battery', models.IntegerField()),
                ('processor', models.CharField(max_length=100)),
            ],
        ),
    ]
