# Generated by Django 5.1.6 on 2025-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_brands_products_images_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones_tablets',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='products/'),
        ),
    ]
