# Generated by Django 5.1.6 on 2025-04-11 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_smartphones_tablets_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pcs',
            name='pc_status',
            field=models.CharField(default='Neuf', max_length=20),
        ),
        migrations.AlterField(
            model_name='pcs',
            name='graphics_card',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pcs',
            name='processor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pcs',
            name='ram',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pcs',
            name='refresh_rate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pcs',
            name='storage',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='pcs',
            name='pc_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.pcrange'),
        ),
    ]
