# Generated by Django 5.1.6 on 2025-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_pcrange_pcs_pc_status_alter_pcs_graphics_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcs',
            name='pc_model',
            field=models.CharField(default='600', max_length=20),
        ),
    ]
