# Generated by Django 5.1.6 on 2025-04-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_pcs_pc_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcs',
            name='pc_model',
        ),
    ]
