# Generated by Django 5.1.6 on 2025-04-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_pcs_pc_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcs',
            old_name='pc_type',
            new_name='clavier',
        ),
        migrations.AddField(
            model_name='pcs',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='products/'),
        ),
    ]
