# Generated by Django 5.1.6 on 2025-06-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='casques_ecouteurs',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='products/'),
        ),
    ]
