# Generated by Django 5.1.6 on 2025-10-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_casques_ecouteurs_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_url',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='products/'),
        ),
    ]
