# Generated by Django 5.1.6 on 2025-10-07 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_remove_images_image_url_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Products.products'),
        ),
    ]
